FROM openjdk:8-jdk-alpine
VOLUME /tmp
EXPOSE 8888
ARG JAR_FILE=target/WebEasyKar-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} scheduler.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/WebEasyKar-0.0.1-SNAPSHOT.jar"]