package com.eazykar.portal.domain.enumeration;

/**
 * The DocumentType enumeration.
 */
public enum DocumentType {
    PROFILE_PIC, PAN, AADHAR, DEMONETISATION_CASH_DEPOSITS, BANK_ACCOUNT_DETAILS, TDS_CERTIFICATES, TAX_PAYMENT_CHALLAN, ORIGINAL_RETURN, DETAILS_OF_NOTICE, ITR_V, GENERAL_DOCUMENTS, INCOME_FROM_OTHER_SOURCES, TAX_SAVINGS_INVESTMENTS, OTHER_DEDUCTIONS, FORM_16, SALARY_CERTIFICATE, FORM_26AS, HOUSE_PROPERTY, CAPITAL_GAIN
}
